### ISSUE TITLE
Performances need to be sorted in descending order by date

### ISSUE THREAD

**Issue by j1mc** [accidentalshakespeare/company-site#56]
i.e., most recent performances should be listed first, and older performances should be listed last. Some possible options include:

- adding a "date" parameter to the frontmatter of each production, and then using this plugin: https://github.com/kylepaulsen/Jekyll-Sort
- adding a "date" parameter to the frontmatter of each production, and using something like this: https://gist.github.com/Phlow/1f27dfafdf2bbcc5c48e .  I think this would require that we use Jekyll collections. https://jekyllrb.com/docs/collections/

I'm open to any working method.

**Comment by jepetersohn** [comment]
I'll work on making that change this week

**Comment by jepetersohn** [comment]
all done! =)

**Comment by TylerSmall19** [comment]
This is not resolved yet.

**Comment by hollabaq86** [comment]
I merged Joan's PR, please let me know if the changes are reflected in staging.  They are showing to be working on my local server.

**Comment by j1mc** [comment]
Confirmed that this now looks correct on staging.accidentalshakespeare.org.

**Comment by j1mc** [comment]
Closing this issue. Thank you, Joan!
