### ISSUE TITLE
Set images to standard image sizes for featured / carousel images

### ISSUE THREAD

**Issue by j1mc** [accidentalshakespeare/company-site#75]
The images used for the carousels are all different sizes, and we should decide on standard image sizes to make the site's appearance more consistent.

**Comment by hollabaq86** [comment]
@jepetersohn I found a site that let's you re-size jpg images, would you happen to have the time to work on this with me?

**Comment by hollabaq86** [comment]
I just pushed up a branch with resized images for the homepage, I'll start working on individual productions on a separate branch

**Comment by hollabaq86** [comment]
This issue has been resolved with the latest [PR to be merged][https://github.com/accidentalshakespeare/company-site/pull/83]
